title: Salted Hoya
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Soltedhoya is an Associate Game Developer in Tokyo, Japan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saltedhoya.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: saltedhoya
github_username: saltedhoya

remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
  - index.md
  - about.md
  - privacy/index.md

style: dark # dark (default), light or hacker

footer: '<a href="https://x.com/saltedhoya">X</a> <a href="https://store.steampowered.com/search/?developer=Salted%20Hoya">Steam</a>'
# google_analytics: UA-NNNNNNNN-N
